import React, { Component } from 'react';
import Typist from 'react-typist';
import '../styles/Main.css';

export class TextPic extends Component {
  render(){
    return(
      <div className="text_pic">
      <Typist>
      ..................................................
      </Typist>
      <Typist>
      .....................:+yhdmdh+....................
      </Typist>
      <Typist>
      ................../odmNNNMMNNNmyo.................
      </Typist>
      <Typist>
      ....HELLO.......-yNNMMMMMMMMMNNMNy.......WORLD!...
      </Typist>
      <Typist>
      ...............+NNNNNmmmNNNNmMNNMNh:..............
      </Typist>
      <Typist>
      ........``````+mmmNds+\\\\\+omNNNMNo..............
      </Typist>
      <Typist>
      ......````````+mmmho+/:::::/+hhmmMNo..............
      </Typist>
      <Typist>
      ....``````````/mmysoo/::::::/yshhNN+..............
      </Typist>
      <Typist>
      ....```````````dhoooosso/:/+ssssshm-```...........
      </Typist>
      <Typist>
      ``````````````,yh++oos/++/+++yssoyy````...........
      </Typist>
      <Typist>
      ``````````````.+y+/:::::++/o/::/oy/``````.........
      </Typist>
      <Typist>
      ```````````````+oo/::::+/:++:::+oo:```````........
      </Typist>
      <Typist>
      ```````````````.-o/::::++/++::/+o-.```````........
      </Typist>
      <Typist>
      `````````````````/+/://++++o///+:`````````........
      </Typist>
      <Typist>
      ``````````````````o+\\\\\\\\\\++````````````......
      </Typist>
      <Typist>
      ``````````````````+oo+\\\:\++os:````````````......
      </Typist>
      <Typist>
      ``````````````````+++osyssyys+o:````````````......
      </Typist>
      <Typist>
      ````````````.-:+/+o+\\\\\\\\\\oo+o+/-.``````......
      </Typist>
      <Typist>
      ``````..--:hmNNh+++\\::::::::/+/++dNNmo:--........
      </Typist>
      <Typist>
      -immmmNNNNNNNNNd\\\\\:-----:\\\\++hNNNNNNNmmmmmm..
      </Typist>
      <Typist>
      NNNNNNNNNNNNNNNNo\\\::-----::\\\\\hNNNNNNNNNNNNmm.
      </Typist>
      <Typist>
      NNNNNNNNNNNNNNNNh:::----------:::oNNNNNNNNNNNNNNm:
      </Typist>
      <Typist>
      NNNNNNNNNNmNNNNNmh\:----------::smNNNNNNNNNNNNNNNs
      </Typist>
      </div>
    );
  }
}
